apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-uid
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
      
  - name: Loki
    type: loki
    uid: loki-uid
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus-uid
          matcherRegex: "request_id=([\\w-]+)"
          name: "Request ID"
          url: "/explore?orgId=1&left={\"datasource\":\"prometheus-uid\",\"queries\":[{\"expr\":\"http_requests_total{request_id=\\\"$${__value.raw}\\\"}\",\"refId\":\"A\"}],\"range\":{\"from\":\"now-1h\",\"to\":\"now\"}}" 